### ISSUE TITLE
TLS CRL are not considered

### ISSUE THREAD

**Issue by nicolatimeus** [mz-automation/lib60870#117]
The library provided support for setting CRL lists, however the CRLs do not seem to be considered during the handshake.
Do they need to be passed here?

https://github.com/mz-automation/lib60870/blob/88e614852b54504cbc84426174b3cbd5dcb04ebf/lib60870-C/src/hal/tls/mbedtls/tls_mbedtls.c#L491

**Comment by mzillgith** [comment]
You are right. Thanks for the hint. Should be fixed now.
