### ISSUE TITLE
Connection drop during TLS renegotiation

### ISSUE THREAD

**Issue by nicolatimeus** [mz-automation/lib60870#118]
I've noticed that if TLS renegotiation timeout is set (for example on the master configuration) the connection is dropped and reopened during the renegotiation procedure. Is this expected?

**Comment by mzillgith** [comment]
It's not expected. I observed that the renegotiation is working when configured at one side (client or server) only. But there is a handshake error when both sides initiate the renegotiation.

**Comment by mzillgith** [comment]
This has been fixed in the meantime.
