### ISSUE TITLE
101 LinkLayerParamter problem

### ISSUE THREAD

**Issue by BluerabbitY** [mz-automation/lib60870#122]
In file `lib60870/lib60870-C/src/iec60870/link_layer/link_layer.c` 1362 line:
`struct sLinkLayerPrimaryUnbalanced{...}` Should the type of member `linkLayerParameters` be `LinkLayerParameters` ?
If I use the current type. 
Create a master
`CS101_Master master = CS101_Master_create(port, NULL, NULL, IEC60870_LINK_LAYER_UNBALANCED);` . I will not be able to modify parameter values using the following method:
```
LinkLayerParameters llParams = CS101_Master_getLinkLayerParameters(master);
llParams->addressLength = 1;
```
It will only modify the parameter values of `master-->linkLayerParameters` and `master-->unbalancedLinkLayer-->linkLayerParameters` but not `master-->transceiver-->linkLayerParameters`.

**Comment by mzillgith** [comment]
Thank you for the hint. It should be fixed now.
