### ISSUE TITLE
memory leak？

### ISSUE THREAD

**Issue by casonyks** [mz-automation/lib60870#124]
Hi,

lib60870-c>src>iec60870>cs101>cs101.c:682

>if (irc) {
>if (self->interrogationHandler(self->interrogationHandlerParameter,
>&(self->iMasterConnection), asdu, InterrogationCommand_getQOI(irc)))
> messageHandled = true;
> }
> else {
> DEBUG_PRINT("Invalid message");
> }

"irc" is not released?

**Comment by mzillgith** [comment]
It's not a memory leak because the memory for irc is staticially allocated (_io).
