### ISSUE TITLE
Memory after new connection in "cs104_server_no_threads.c"

### ISSUE THREAD

**Issue by flaviofvillaca** [mz-automation/lib60870#129]
Dear Sirs,

I'm testing the library for a possible use in one of our products and I found what I think is a memory leak.

I built the example "cs104_server_no_threads.c" with the following setup:

in file "lib60870_config.h"
```
#define CONFIG_USE_THREADS 0
#define CONFIG_USE_SEMAPHORES 0
#define CONFIG_CS104_SUPPORT_SERVER_MODE_SINGLE_REDUNDANCY_GROUP 1
#define CONFIG_CS104_SUPPORT_SERVER_MODE_MULTIPLE_REDUNDANCY_GROUPS 1
#define CONFIG_CS104_SUPPORT_SERVER_MODE_CONNECTION_IS_REDUNDANCY_GROUP 1
```

And in "main" function line 223 of the file "cs104_server_no_threads.c" I set the following:
`CS104_Slave_setServerMode(slave, CS104_MODE_CONNECTION_IS_REDUNDANCY_GROUP);
`

So, when I run the example "cs104_server_no_threads.c", every time I make a new connection to the server, I can see a increment in memory that I can't see a corresponding decrement when disconnecting.

I found that in file "cs104_slave.c" line 3209, there is code to allocate RAM for the queues for the opening connection but I couldn't find where this memory is getting free.

```
#if (CONFIG_CS104_SUPPORT_SERVER_MODE_CONNECTION_IS_REDUNDANCY_GROUP == 1)
                if (self->serverMode == CS104_MODE_CONNECTION_IS_REDUNDANCY_GROUP) {
                    lowPrioQueue = MessageQueue_create(self->maxLowPrioQueueSize);
                    highPrioQueue = HighPriorityASDUQueue_create(self->maxHighPrioQueueSize);
                }
#endif
```

Thanks in advance.

**Comment by mzillgith** [comment]
Thank you for the hint. The memory leak should be fixed now.

**Comment by flaviofvillaca** [comment]
Hi @mzillgith,

Thank you for fast response. I'll test and give feedback after.

**Comment by flaviofvillaca** [comment]
Hi @mzillgith,

The tests was successful. No memory leaks. Thanks.
