### ISSUE TITLE
CP56Time2a_createFromMsTimestamp leaking memory

### ISSUE THREAD

**Issue by tautvilis** [mz-automation/lib60870#152]
CP56time2a created by CP56Time2a_createFromMsTimestamp leaks memory as it isn't destroyed like information object or asdu. 
Is there a specific destroy function for it? Or the only way is to use free()?

**Comment by m-unkel** [comment]
You could pass a reference to CP56Time2a_createFromMsTimestamp.

```
{
  sCP56time2a time;
  CP56Time2a_createFromMsTimestamp(&time, 1711111111111);
}
```
