### ISSUE TITLE
Incorrect use of station interrogation procedure

### ISSUE THREAD

**Issue by alikovvl** [mz-automation/lib60870#16]
IEC 60870-5-101
Table 17 – ASDUs involved in the station interrogation procedure

All ASDUs for station interrogation procedure are listed.
MeasuredValueScaledWithCP56Time2a and SinglePointWithCP56Time2a not allowed. 

```private static bool interrogationHandler(object parameter, ServerConnection connection, ASDU asdu, byte qoi)```
This is an incorrect example

**Comment by mzillgith** [comment]
Thanks for the hint. I fixed the examples.
