### ISSUE TITLE
when i comment delay funtion in example(simple_client), it cause Segmentation fault !

### ISSUE THREAD

**Issue by ckoh01** [mz-automation/lib60870#2]
hello,
in the  simple_client example, i compiled sourcecode which two delay funtions "Thread_sleep(5000)" at line 89 and 93 were commented  with make in ubuntu12.04 .  the program run to Segmentation fault (core dumped).

when debug  with gdb , it throw below info.

(gdb) bt
#0  0xb7e79410 in __GI___libc_free (mem=0x8060128) at malloc.c:2984
#1  0x08056bdd in Memory_free (memb=0x8060128) at src/common/lib_memory.c:79
#2  0x08056a8b in Thread_destroy (thread=0x8060128)
    at src/hal/thread/linux/thread_linux.c:114
#3  0x08049712 in T104Connection_close (self=0x8060008)
    at src/iec60870/t104/t104_connection.c:321
#4  0x08049725 in T104Connection_destroy (self=0x8060008)
    at src/iec60870/t104/t104_connection.c:328
#5  0x08048ffb in main (argc=1, argv=0xbffff334) at simple_client.c:118

coredumped at free() funtion in glibc , could you give some cue.

BTW,  v0.9.3 does not get this problem.

**Comment by mzillgith** [comment]
Hello. There was bug in memory allocation introduced by refactoring. Seems to be solved now.
