### ISSUE TITLE
example TLS server/client combo unable to connect

### ISSUE THREAD

**Issue by msichal** [mz-automation/lib60870#22]
I've been trying to use provided C TLS examples, but I had no luck in getting them to comunicate.

```
lib60870-C/examples/tls_server$ ./tls_server
New connection from 127.0.0.1
Close connection
```

```
lib60870-C/examples/tls_client$ ./tls_client
Connect failed!
exit
```

Tried on two machines with different GCCs, they compile fine, but won't connect as shown above.
Any ideas on what might be the problem or how to debug it?

**Comment by mzillgith** [comment]
There has been a problem with the example client configuration that caused the client to check for the wrong certificate. Should be fixed now.
