### ISSUE TITLE
SegFault in cs104_server

### ISSUE THREAD

**Issue by Nanahara** [mz-automation/lib60870#25]
Hello,

I have a Segmentation fault when I execute cs104_server example with cs104_client example (version 2.0.0, it works in 0.9.7)

here it is the valgrind result :
==30968== Memcheck, a memory error detector
==30968== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==30968== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==30968== Command: ./cs104_server
==30968== 
New connection from 127.0.0.1
==30968== Thread 3:
==30968== Invalid read of size 8
==30968==    at 0x41A746: HighPriorityASDUQueue_resetConnectionQueue (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x41B9AD: handleMessage (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x41BFB8: connectionHandlingThread (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x41D6B5: destroyAutomaticThread (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x4E3D063: start_thread (pthread_create.c:309)
==30968==  Address 0x18 is not stack'd, malloc'd or (recently) free'd
==30968== 
==30968== 
==30968== Process terminating with default action of signal 11 (SIGSEGV)
==30968==  Access not within mapped region at address 0x18
==30968==    at 0x41A746: HighPriorityASDUQueue_resetConnectionQueue (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x41B9AD: handleMessage (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x41BFB8: connectionHandlingThread (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x41D6B5: destroyAutomaticThread (in /home/doerra/HbsSystemTools/lib60870-2.0.0/lib60870-C/_build_/examples/cs104_server/cs104_server)
==30968==    by 0x4E3D063: start_thread (pthread_create.c:309)
==30968==  If you believe this happened as a result of a stack
==30968==  overflow in your program's main thread (unlikely but
==30968==  possible), you can try to increase the size of the
==30968==  main thread stack using the --main-stacksize= flag.
==30968==  The main thread stack size used in this run was 8388608.
==30968== 
==30968== HEAP SUMMARY:
==30968==     in use at exit: 1,624 bytes in 15 blocks
==30968==   total heap usage: 76 allocs, 61 frees, 11,328 bytes allocated
==30968== 
==30968== LEAK SUMMARY:
==30968==    definitely lost: 0 bytes in 0 blocks
==30968==    indirectly lost: 0 bytes in 0 blocks
==30968==      possibly lost: 544 bytes in 2 blocks
==30968==    still reachable: 1,080 bytes in 13 blocks
==30968==         suppressed: 0 bytes in 0 blocks
==30968== Rerun with --leak-check=full to see details of leaked memory
==30968== 
==30968== For counts of detected and suppressed errors, rerun with: -v
==30968== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Killed

**Comment by mzillgith** [comment]
Hello,
What did you do to provoke this error? I was not able to reproduce it. The cs104_server and cs104_client example seem to work fine together.

**Comment by Nanahara** [comment]
Hello,
After rebuild library, I have not reproduced this error. Maybe I have done something wrong the first time.

For build I use gcc 4.9.2 on Debian Jessie and add std=gnu99 C flag in CMakeFiles.txt.

**Comment by mzillgith** [comment]
Ok. Thanks for the info. So I guess the build environment got somewhat corrupted while updating the code to the newer version.
