### ISSUE TITLE
Memory issue ?

### ISSUE THREAD

**Issue by Nanahara** [mz-automation/lib60870#27]
Hello,
I observe a strange behaviour with multi_client_server example. The memory of program increase according to the number of simultaneous connected clients (I tested with 1 to 5 simultaneous clients). But after client disconnections, the memory does not decrease.

I use top or htop command and I see the VIRT and RES column.

NB : Valgrind doesn't detect leak memory.

**Comment by mzillgith** [comment]
Hi,
afaik the "virt" and "res" numbers don't reflect the memory actual used by the application. It also depends on the implementation of malloc/free that are used by default for memory allocation, when memory is requested and released from the system. If valgrind does't show a memory leak I would expect there isn't one.
