### ISSUE TITLE
ARM Cross compile

### ISSUE THREAD

**Issue by liuz888** [mz-automation/lib60870#29]
/root/iotbase/thirdpart/lib60870/lib60870-2.0.0/lib60870-C/src/hal/serial/linux/serial_port_linux.c:44:20: error: field ‘timeout’ has incomplete type
     struct timeval timeout;
                    ^
/root/iotbase/thirdpart/lib60870/lib60870-2.0.0/lib60870-C/src/hal/serial/linux/serial_port_linux.c: In function ‘SerialPort_readByte’:
/root/iotbase/thirdpart/lib60870/lib60870-2.0.0/lib60870-C/src/hal/serial/linux/serial_port_linux.c:241:5: error: unknown type name ‘fd_set’
     fd_set set;

**Comment by mzillgith** [comment]
I cannot reproduce the problem. For me it compiles fine on ARM linux box.
