### ISSUE TITLE
Some configuration mistakes in cs104_slave.c

### ISSUE THREAD

**Issue by igor-sladkov** [mz-automation/lib60870#33]
I found some configuration mistakes in cs104_slave.c.
Strings CONFIG_CS104_SUPPORT_SERVER_MODE_CONNECTION_IS_REDUNDANCY_GROUP
in some places have been improperly replaced by CONFIG_CS104_SUPPORT_SERVER_MODE_SINGLE_REDUNDANCY_GROUP.
This applies to lines 50, 635, 771, 2200 and maybe others.

**Comment by mzillgith** [comment]
Thank you for the hints. Should be fixed now.
