### ISSUE TITLE
Closing a specific master connection

### ISSUE THREAD

**Issue by pbdqpbdq** [mz-automation/lib60870#35]
How can a CS104 slave close a specific incoming connection from a master?
`IMasterConnection` has methods for sending responses and querying parameters but not for closing the connection - if, say, slave detected some unrecoverable condition during exchange.

**Comment by mzillgith** [comment]
I am a bit surprised why the server should close a specific connection? Actually if there is a problem with the connection the server closes the connection automatically. So at the moment I cannot imagine what could be a reasonable application for a dedicated API function. Can you provide some example for an "unrecoverable condition during exchange"?

**Comment by rojer** [comment]
@mzillgith well, there are a million reasons, really, including server wanting to shed some load by bumping low-priority clients.
but in my specific case, if i find that the client tries to use wrong Common Address, i want to drop the connection because clearly something is wrong and misconfigured.

**Comment by pbdqpbdq** [comment]
@mzillgith well, there are a million reasons, really, including server wanting to shed some load by bumping low-priority clients.
but in my specific case, if i find that the client tries to use wrong Common Address, i want to drop the connection because clearly something is wrong and misconfigured.

**Comment by pbdqpbdq** [comment]
FWIW, the simple patch above works for me.

**Comment by mzillgith** [comment]
Yes. That makes sense. I will check your patch. Thanks.
