### ISSUE TITLE
Timeout handling issue

### ISSUE THREAD

**Issue by n7nexus** [mz-automation/lib60870#37]
There is an issue with timeout handling in cs104_connection.c.
In `static bool handleTimeouts(CS104_Connection self)` we can get situation when 
`if ((currentTime - self->sentASDUs[self->oldestSentASDU].sentTime) >= (uint64_t) (self->parameters.t1 * 1000))` condition does not work as expected.
Expression `currentTime - self->sentASDUs[self->oldestSentASDU].sentTime` could return negative result (and that happened, when I investigated an issue in some project). So I propose look at signed arithmetics and change this condition with something like that: 
`if ((int32_t)(currentTime - self->sentASDUs[self->oldestSentASDU].sentTime) >= (self->parameters.t1 * 1000)) {`

**Comment by mzillgith** [comment]
Thanks for the hint. I added some additional checks. I think this can happen when the system time is set to the past.
