### ISSUE TITLE
Can't compile example

### ISSUE THREAD

**Issue by ZRomik** [mz-automation/lib60870#38]
When I try to compile example in folder  "cs_104_server" I see error message:"socket_win32.c|100|undefined reference to `__imp_select'|"
What can I do to resolve this error?
I'm developing in Code::Blocks 17.12

**Comment by ZRomik** [comment]
In all source file I'm not find text "__imp_select"

**Comment by mzillgith** [comment]
Looks like you didn't link with the winsock library.

**Comment by mzillgith** [comment]
This is only for the visual studio compiler.
