### ISSUE TITLE
possible deadlock in mode CONNECTION_IS_REDUNDANCY_GROUP

### ISSUE THREAD

**Issue by m-unkel** [mz-automation/lib60870#40]
I have a threaded application where one thread produces new ASDUs and another thread is responsible for slave connection handling. The server is running in the following mode:
CONFIG_CS104_SUPPORT_SERVER_MODE_CONNECTION_IS_REDUNDANCY_GROUP = 1

For low priority ASDUs (e.i. periodic measurements) I test CS104_Slave_getOpenConnections() > 0 in prior to calling CS104_Slave_enqueueASDU(slave, asdu).

It is a race condition that arises if a client closes the connection:
 -> connectionHandlingThread: connectionEventHandler gets called (cs104_slave.c 2526)
 -> connectionHandlingThread: release / frees the queue and the corresponding queueLock semaphore (cs104_slave.c 2535f)
 -> MyThread: CS104_Slave_getOpenConnections() is still 1
 -> MyThread: tries to send an ASDU by calling CS104_Slave_enqueueASDU(slave, asdu)
 -----> locks self->openConnectionsLock (cs104_slave.c 3184)
 -----> calls MessageQueue_enqueueASDU
 -----------> waits forever for self->queueLock (DEADLOCK) (cs104_slave.c 269)
 -> connectionHandlingThread: calls CS104_Slave_removeConnection(self->slave, self) (cs104_slave.c 2540)
 ----> waits forever for self->openConnectionsLock (DEADLOCK) (cs104_slave.c 2427)

On a x86 PC the race condition isn't happening that often, but it is easily reproducible on a raspberry pi (armhf32). 

I could bypass this situation with an own connectionMap maintained within the connectionEventHandler-callback to test if there is an active connection or not to be able to discard new ASDUs, but I think you might want to fix this issue.

**Comment by mzillgith** [comment]
Thank you for the hint. Should be solved now.
