### ISSUE TITLE
Uninitialized slave queue in mode CONNECTION_IS_REDUNDANCY_GROUP

### ISSUE THREAD

**Issue by m-unkel** [mz-automation/lib60870#47]
In mode CONNECTION_IS_REDUNDANCY_GROUP:

If you create a slave (CS104_Slave_create) and destroy the slave (cs104_Slave_destroy) without calling start (CS104_Slave_start) inbetween it will produce a segmentation fault in trying to destroy the queue witch pointer was neither initialized with NULL nor instanciated (instantiation is done within the start function).
I have created a fix with a pull requests (#45 pull request) witch is awaiting your review since two weeks..
Thanks in advance.

**Comment by mzillgith** [comment]
Thank you for the fix!
