### ISSUE TITLE
M_ST_TB_1 not working

### ISSUE THREAD

**Issue by atyl28** [mz-automation/lib60870#49]
When attempting to send the M_ST_TB ASDU wire shark reports it as Invalid APDU length.

When I remove the time stamp and send as M_ST_NA wire shark recognise the frame correctly.

[104dump.pcap.zip](https://github.com/mz-automation/lib60870/files/3462140/104dump.pcap.zip)

**Comment by mzillgith** [comment]
Thanks for reporting the bug. Should be fixed now.
