### ISSUE TITLE
cs104 server examples do not work on Linux because of default backlog=0

### ISSUE THREAD

**Issue by jsopenrb** [mz-automation/lib60870#50]
By default `backlog` parameter for `listen` is set to 0. This causes the server not to accept any clients. There's a setter function `ServerSocket_setBacklog` but it does not seem to be used anywhere.

**Comment by mzillgith** [comment]
That's strange. I used this setting on many different linux systems and never had that problem.

**Comment by rojer** [comment]
just ran into the same issue. indeed, it works on ubuntu with kernel 5.4 but not on our embedded target with 4.14.

**Comment by mzillgith** [comment]
@rojer  You mean it doesn't work with backlog set to 2?

**Comment by rojer** [comment]
no-no, now it does.
