### ISSUE TITLE
LinkLayerBalanced address cannot be changed

### ISSUE THREAD

**Issue by nicolatimeus** [mz-automation/lib60870#51]
If the library is used in 101 balanced master mode, there seems to be no way for changing the link layer address used by the LinkLayerSecondaryBalanced part of LinkLayerBalanced

`CS101_Master_setOwnAddress()` only modifies `sCS101_Master::linkLayer` and does not change `sCS101_Master::balancedLinkLayer`, for this reason the link layer address of frames sent in reverse direction by the library is always 0.

I may have missed something but I’ve found no way to configure that address using the public API, is this behaviour intentional?

**Comment by mzillgith** [comment]
Yes, there seems to be a bug. But the address in the response to a primary message from the slave should be the slave address. `CS101_Master_setSlaveAddress` should be used to set it.
I will fix it.
