### ISSUE TITLE
On linux, socket is closed twice after connect timeout

### ISSUE THREAD

**Issue by paluke** [mz-automation/lib60870#52]
In the "socket_linux.c" file socket descriptor is closed in case of connection timeout at the end of _Socket_connect_ function. And then this socket descriptor is closed again in function _Socket_destroy_. But it descriptor may be already reused in other thread.
In files "socket_win32.c" and "socket_bsd.c" there is no closing socket on timeout in _Socket_connect_.

**Comment by mzillgith** [comment]
Thanks for the hint. It should be fixed now.
