### ISSUE TITLE
Bitstring32X_create functions do not set quality

### ISSUE THREAD

**Issue by nicolatimeus** [mz-automation/lib60870#63]
The `BitString32_create`, `Bitstring32WithCP24Time2a_create`, `Bitstring32WithCP56Time2a_create` functions do not provide a `QualityDescriptor` argument to set the quality.
Are there other ways to set the quality field?

**Comment by mzillgith** [comment]
You are right, there is no way to set the quality. I added a "quality" argument to the create functions.

**Comment by nicolatimeus** [comment]
Thank you for the prompt fix.
The changes in the fix commit does not seem backwards compatible, this should mean that next library version will be 3.X right?

**Comment by mzillgith** [comment]
Yes. You are right. Maybe it is better to revert the backward incompatible API change for now and just add a setter function for quality (and default quality is "good") and change the API later for version 3. as the next version was planned to be 2.3 with some minor changes.

**Comment by nicolatimeus** [comment]
Makes sense to me
