### ISSUE TITLE
Access to null pointer, when server is created, but isn't running

### ISSUE THREAD

**Issue by eremenko789** [mz-automation/lib60870#64]
`
auto m_server = CS104_Slave_create(m_maxLowPrioQueuSize, m_maxHighPrioQueuSize);
CS104_Slave_destroy(m_server)
`

In this case the self->asduQueue is null and in MessageQueue_releaseAllQueuedASDUs() try to access null pointer. In result, we have got undefined behavior.

**Comment by mzillgith** [comment]
Thanks for the hint!
