### ISSUE TITLE
Check Bitstring32X encoding

### ISSUE THREAD

**Issue by nicolatimeus** [mz-automation/lib60870#65]
I think following line

https://github.com/mz-automation/lib60870/blob/d787cb56e3768e75bc4c8a525cf403c0811b4c69/lib60870-C/src/iec60870/cs101/cs101_information_objects.c#L1183

should be changed to 

`uint32_t value = self->value`

otherwise the following code that extracts the single bytes might produce incorrect results when `(int) self->value` is negative.

This same applies to the bitstring variants with time tags.

**Comment by mzillgith** [comment]
I my tests I found no differences in the encoding when changing the type from int to uint32. I changed it anyway as you suggested because there was no good reason to convert the type here.

**Comment by nicolatimeus** [comment]
I noticed differences trying to encode the `0xffffffff` value, can you please add that value to the unit tests as well?

**Comment by mzillgith** [comment]
Of course you are right. My test case didn't catch the error.
