### ISSUE TITLE
Issues with CS104 slave MessageQueue

### ISSUE THREAD

**Issue by nicolatimeus** [mz-automation/lib60870#67]
The code path containing the following line in `MessageQueue_enqueueASDU`:

https://github.com/mz-automation/lib60870/blob/130aca0878aa09ce22c9458d1909ec794bcc5ed5/lib60870-C/src/iec60870/cs104/cs104_slave.c#L240

leaves the function without updating the value of `self->lastInBufferEntry`.

If this happens, subsequent calls to the `MessageQueue_X` functions that rely on the fact that `self->lastInBufferEntry` is correct for traversing the queue will probably cause undefined behaviour.

I think this can be fixed by setting

`self->lastInBufferEntry = nextMsgPtr;`

before leaving the function.
This is based on the assumption that the entry that the function is about to add will also be "last in the buffer", which should be correct if the other invariants are respected.

Moreover, i noticed that the code path containing the following line

https://github.com/mz-automation/lib60870/blob/130aca0878aa09ce22c9458d1909ec794bcc5ed5/lib60870-C/src/iec60870/cs104/cs104_slave.c#L236

does not update `self->oldestTimestamp`, is this correct?

**Comment by mzillgith** [comment]
The `lastInBufferEntry` is the address of the entry with the highest address in the buffer. It is not touched in this code path by intention.

**Comment by nicolatimeus** [comment]
Maybe I did not understand the code correctly, I will recheck it but if I'm not wrong, if the control enters that code path, the `lastInBufferEntry` is going to be removed.
In this case, `lastInBufferEntry` should be set to the address of the entry with the highest address in the buffer after the update.

**Comment by nicolatimeus** [comment]
Commit d400acf is a good improvement but there are still some issues with the queue.

Please check branch fix_message-queue [1] on my fork.

Commit [2] sets up an environment for stress testing with a modified version of the threadless server example and the client example:

* The server enqueues every millisecond a random number of ASDUs each containing a random number of information objects.
* The server includes a monotonically increasing sequence number in every informantion object.
* The client checks received sequence numbers for detecting message losses.

Commit [2] contains no changes in queue implementation, during my tests with this commit the server reliably crashes with a SIGSEGV shortly after client connection. Valgrind reports a couple of invalid memory accesses.

I've added some changes to the queue in commit [3], the test scenario seems to run successfully with them and Valgrind does not seem to complain about anything.

Please try to running the test scenario to reproduce and review my changes, I can provide more details on them and on the issues I've found if needed.

[1] https://github.com/nicolatimeus/lib60870/tree/fix_message-queue
[2] https://github.com/nicolatimeus/lib60870/commit/fa8f6a89061b5e674d385c2e0c4255dbfa35d339
[3] https://github.com/nicolatimeus/lib60870/commit/eb7b5b062412ee7d30cc504afedd021fe41f1c98

**Comment by mzillgith** [comment]
Thank you for the test setup. It helped a lot for identifying the problems in the queue. My test cases didn't catch the problem because they only added messages of similar sizes. I will add more test cases for the queue handling.

**Comment by nicolatimeus** [comment]
Thank you for the changes, I've started some testing and found no problems so far.
Just one thing, after 
https://github.com/mz-automation/lib60870/blob/0c0b2afa1625adae1e4e2fa393fe6c93c7004e21/lib60870-C/src/iec60870/cs104/cs104_slave.c#L443
shouldn't we copy back the updated value to the queue?

**Comment by mzillgith** [comment]
> Thank you for the changes, I've started some testing and found no problems so far.
> Just one thing, after
> 
> https://github.com/mz-automation/lib60870/blob/0c0b2afa1625adae1e4e2fa393fe6c93c7004e21/lib60870-C/src/iec60870/cs104/cs104_slave.c#L443
> 
> shouldn't we copy back the updated value to the queue?

Thanks, You are right. I added the missing statement.

**Comment by aflteam** [comment]
Hello @nicolatimeus, 

I am facing message que problems as well #77.  Which version did you tested? Yours and mine issue have similarities, but i could not find an answer.

**Comment by mzillgith** [comment]
I guess this issue is solved.
