### ISSUE TITLE
How to send Broadcast GI (General Interrogation) from CS101_master Unbalanced?

### ISSUE THREAD

**Issue by smit-github** [mz-automation/lib60870#69]
I had tried example code for cs101_master_unbalanced. Here i want to make broadcast message to be send to slave but i cant able to send it by making below statement
`            /* Send a general interrogation to a specific slave */
            if (CS101_Master_isChannelReady(master, local_address)) {
		  printf("Send general interrogation \n");	
                CS101_Master_useSlaveAddress(master, 0xFF);
                CS101_Master_sendInterrogationCommand(master, CS101_COT_ACTIVATION, 0xFFFF, IEC60870_QOI_STATION);
                CS101_Master_run(master);`

Can you please help me to send broadcast GI (General Interrogation) from Master to slave

**Comment by mzillgith** [comment]
Same as #88. Should work now.
