### ISSUE TITLE
Library integration

### ISSUE THREAD

**Issue by salfetko** [mz-automation/lib60870#71]
Hello. Try to use this library in my project that need 104 client. Have some problems:

1) Headers have interdependence, e.g. 'CP56Time2a' defined in "iec60870_common.h", but used freely in "cs101_information_objects.h" and 'IEC60870_5_TypeID' defined in "cs101_information_objects.h", but used freely in" iec60870_common.h".

`cs101_information_objects.h:1550:1: error: ‘CP56Time2a’ does not name a type
cs101_information_objects.h:928:9: error: ‘BinaryCounterReading’ has not been declared
cs101_information_objects.h:2104:28: error: ‘CS101_AppLayerParameters’ was not declared in this scope`

2) There are missed value and quality accessors for ASDU with 'CP56Time2a'

**Comment by pechezerov** [comment]
You should use only 
`#include "cs104_slave.h"`
Isn't it help you?

**Comment by salfetko** [comment]
> You should use only
> `#include "cs104_slave.h"`
> Will this help you?

Yes, thank you!
