### ISSUE TITLE
Incorrect information object when use quality IEC60870_QUALITY_OVERFLOW

### ISSUE THREAD

**Issue by eremenko789** [mz-automation/lib60870#72]
In case of additional information with quality IEC60870_QUALITY_OVERFLOW we have unexpected value and quality after get it. In case of others quality all is ok.
`
CS101_ASDU newAsdu = CS101_ASDU_create(&par, false, CS101_COT_INTERROGATED_BY_STATION,
                                           0, 1, true, true);
    CS101_ASDU_addInformationObject(newAsdu, (InformationObject) SinglePointInformation_create(nullptr, 301, true, IEC60870_QUALITY_OVERFLOW));
    InformationObject io = CS101_ASDU_getElement(newAsdu, 0);
    if (io)
        qDebug() << InformationObject_getObjectAddress(io)  // out: 301
                 << SinglePointInformation_getValue((SinglePointInformation)io) // out: false expect: true
                 << SinglePointInformation_getQuality((SinglePointInformation)io); // out: 0 expect: 1

CS101_ASDU newAsdu = CS101_ASDU_create(&par, false, CS101_COT_INTERROGATED_BY_STATION,
                                           0, 1, true, true);
    CS101_ASDU_addInformationObject(newAsdu, (InformationObject) DoublePointInformation_create(nullptr, 301, IEC60870_DOUBLE_POINT_ON, IEC60870_QUALITY_OVERFLOW));
    InformationObject io = CS101_ASDU_getElement(newAsdu, 0);
    if (io)
        qDebug() << InformationObject_getObjectAddress(io)  // out: 301
                 << DoublePointInformation_getValue((DoublePointInformation)io) // out: 3 expect: 2
                 << DoublePointInformation_getQuality((DoublePointInformation)io); // out: 0 expect: 1
`

**Comment by mzillgith** [comment]
Hello,
single point information and double point information have no "overflow" quality flag. Setting it will overwrite the value as the value and quality are encoded in the same byte. I will fix it so that not used quality flags are ignored.
