### ISSUE TITLE
StepCommandWithCP56Time2a_destroy wrong argument type

### ISSUE THREAD

**Issue by salfetko** [mz-automation/lib60870#74]
StepCommandWithCP56Time2a_destroy in cs101_information_objects.c have a wrong argument type:
`StepCommandWithCP56Time2a_destroy(StepCommand self)`
must by
`StepCommandWithCP56Time2a_destroy(StepCommandWithCP56Time2a self)`

**Comment by mzillgith** [comment]
Thanks for the hint!
