### ISSUE TITLE
Missed "tls_socket.h" in CMakeLists.txt for installation

### ISSUE THREAD

**Issue by salfetko** [mz-automation/lib60870#76]
Header "lib60870-C/src/inc/api/cs104_connection.h" have include
`#include "tls_socket.h"`
but on install that file not copying (build-install using only cmake).

Looks like API_HEADERS miss them in main CMakeLists.txt:72

**Comment by mzillgith** [comment]
Thanks for the hint! The include is not required there and I removed it.
