### ISSUE TITLE
Processing with unsupported ASDU types

### ISSUE THREAD

**Issue by igor-sladkov** [mz-automation/lib60870#8]
How can I get the data from ASDU for unsupported types?
I need to implement file transfer functions. The only way to get information from a payload is ASDU_getElement(), but it works with a limited set of types. asduHandler registered by Slave_setASDUHandler() can't directly access the data, because the declaration of sASDU is private.

**Comment by mzillgith** [comment]
At the moment there is no mean to access the data for the unsupported/private types. I will add a generic information object type that can be used for that. I am also currently working on the file transfer support, so that at least the F_... information object parsing will be supported soon.

**Comment by mzillgith** [comment]
Handling unsupported ASDU types is now possible with CS101_ASDU_getPayload amd CS101_ASDU_getPayloadSize functions.
