### ISSUE TITLE
Visual Studio 2019 Solution available ?

### ISSUE THREAD

**Issue by Noschvie** [mz-automation/lib60870#83]
Hello,
is there a "Visual Studio 2019 Solution" available for that ? I'm not familiar with make, sorry ...
thanks, Norbert

**Comment by mzillgith** [comment]
You can use cmake to create a visual studio solution.

You have to install cmake. Then follow the instructions in the README.

When calling cmake you can use the following command line:

`  cmake -G "Visual Studio 16 2019" ..`
 
This will create a visual studio solution file.

**Comment by Noschvie** [comment]
Visual Studio solution file successfully created, thanks.
