### ISSUE TITLE
Server Examples : Should I release ASDU after CS104_Slave_enqueueASDU?

### ISSUE THREAD

**Issue by ditupao** [mz-automation/lib60870#84]
In all server examples except cs104_server_no_threads.c, after calling CS104_Slave_enqueueASDU, always has CS101_ASDU_destroy afterwards.
```
       /* Add ASDU to slave event queue - don't release the ASDU afterwards!
         * The ASDU will be released by the Slave instance when the ASDU
         * has been sent.
         */
        CS104_Slave_enqueueASDU(slave, newAsdu);

        CS101_ASDU_destroy(newAsdu);
```
But before calling CS104_Slave_enqueueASDU, always exists a block of comment telling us not to release the ASDU just created.
Should I follow the comment (remove the CS101_ASDU_destroy line), or just call CS101_ASDU_destroy each time?

**Comment by mzillgith** [comment]
The comments were wrong! You have to call the _CS101_ASDU_destroy_ when you no longer need it. This behaviour was changed in the past but I forgot to update the comments.

**Comment by ditupao** [comment]
Thanks.
