### ISSUE TITLE
CS101_Master: hasNextBroadcastToSend set to true but never used

### ISSUE THREAD

**Issue by nnminh171298** [mz-automation/lib60870#88]
As titled. I am trying to send a broadcast clock sync command but fail. After some digging, it seems that the function `LinkLayerPrimaryUnbalanced_sendNoReply()` set the `hasNextBroadcastToSend` flag, but the flag is never considered anywhere.

**Comment by mzillgith** [comment]
Thanks for the hint. The broadcast command should now work.
