### ISSUE TITLE
C# big endian problem

### ISSUE THREAD

**Issue by zhenghongzhi** [mz-automation/lib60870#9]
Thank you for this wonderful lib60870.
I'm using it in mono environment as Server. I receive data from client with big-endian.
Such as float of 57.74 is 42 66 F5 C3.
Any plan to support big-endian of .Net version?

Thank you!

**Comment by mzillgith** [comment]
In my understanding of the standard little-endian encoding should always be used - as specified in 60870-5-101: "Mode 1 (least significant octet first), as defined in 4.10 of IEC 60870-5-4, is used exclusively in
this companion standard."
Do you have a suggestion for this issue?

**Comment by zhenghongzhi** [comment]
I think it's the client that does not follow the rules as two IEC104 simulators send float in little-endian.
I read IEC 60870-5-104 only and endian is not specified in this doc. 
I modify a few lines of lib60870 to fit my client. 
Thank you
